### ISSUE TITLE
There is a release 5.2.1 already

### ISSUE THREAD

**Issue by jeff-pf** [MihailRomanov/SharpDevelop#22]
Just in case you did not know.

https://github.com/mgeee35/SharpDevelop-5.2.1

**Comment by MihailRomanov** [comment]
Thank you for this link! 

Yes I didn't known about this repo (it have not any references with initial repo https://github.com/icsharpcode/SharpDevelop). Before  start my fork I tried to find any alive forks for SharpDevelop, but found nothing.

Unfortunately repository by your link can't help me - it have only build artifacts (not sources) and (as I understood) include the same changes as https://github.com/MihailRomanov/SharpDevelop/releases/tag/5.2-Beta

But the fact that 2 years ago there were people interested in SharpDevelop is  **very-very inspiring**!!!
This means that my efforts can also be useful!

So thank you again for your interest and for the link!!
